depends:
    - serial-can-bridge
    - serial-datagram
    - crc

target.arm:
    - src/board.c
    - src/main.c
    - src/bridge.c
    - src/usbcfg.c

include_directories:
    - src/

dependency-dir: ./

templates:
    include.jinja: include.mk
