depends:
    - serial-can-bridge
    - serial-datagram
    - crc

target.arm:
    - src/board.c
    - src/main.c
    - src/bridge.c
    - src/usbcfg.c
    - src/exti.c
    - src/sensors/mpu60X0.c
    - src/sensors/ms5611.c
    - src/sensors/hmc5883l.c
    - src/sensors/onboardsensors.c

include_directories:
    - src/

dependency-dir: ./

templates:
    include.jinja: include.mk
